// Generated by CoffeeScript 1.9.3
(function() {
  'use strict';
  var FsConnector, path, uuid;

  path = require('path');

  uuid = require('node-uuid');

  FsConnector = (function() {
    function FsConnector(params, deps) {
      this.files = (deps != null ? deps.fs : void 0) || require('waferpie-utils').Files;
      this.prefix = path.join(params.domain, params.resource);
      try {
        this.files.createDirIfNotExists(params.domain);
      } catch (_error) {}
      try {
        this.files.createDirIfNotExists(this.prefix);
      } catch (_error) {}
    }

    FsConnector.prototype.create = function(data, callback) {
      var e, file, id;
      id = String(data.id) || (order + "_" + (uuid.v4().substr(-12)));
      file = path.join(this.prefix, id);
      if (this.files.isFile(file)) {
        return callback('File already exists.');
      }
      try {
        this.files.createFileIfNotExists(file, JSON.stringify(data));
        return callback(null, true);
      } catch (_error) {
        e = _error;
        return callback(e);
      }
    };

    return FsConnector;

  })();

  module.exports = FsConnector;

}).call(this);
